### ISSUE TITLE
Minimum title length also Limits Tags

### ISSUE THREAD

**Issue by GH-Rake** [Zachman61/MinimumThreadTitleLength#2]
This plugin has a bug, it limits not just the thread title, it limits the tags too

![image](https://user-images.githubusercontent.com/15186628/90298834-acc4e400-de61-11ea-862e-3db059b8730e.png)

**Comment by Zachman61** [comment]
I cannot reproduce this. Make sure you aren't confusing the minimum tags forum node option.
<img width="985" alt="Screen Shot 2020-08-14 at 7 19 16 PM" src="https://user-images.githubusercontent.com/1216404/90299175-2c06e780-de63-11ea-8a5a-9aa032f56e89.png">

**Comment by GH-Rake** [comment]
I'm an actual idiot, sorry.
